CREATE TABLE IF NOT EXISTS user_types (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS user_type_id BIGINT;
ALTER TABLE users DROP COLUMN IF EXISTS role;

CREATE TABLE IF NOT EXISTS restaurants (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    cuisine_type VARCHAR(255) NOT NULL,
    opening_hours VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users(id)
);

ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS cuisine_type VARCHAR(255);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS opening_hours VARCHAR(255);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS owner_id BIGINT;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE restaurants ALTER COLUMN active SET DEFAULT TRUE;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE restaurants ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE restaurants ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS phone VARCHAR(255) DEFAULT '';
ALTER TABLE restaurants ALTER COLUMN phone SET DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_restaurants_owner_id ON restaurants(owner_id);

CREATE TABLE IF NOT EXISTS menu_items (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    available_only_in_restaurant BOOLEAN NOT NULL DEFAULT FALSE,
    photo_path VARCHAR(500),
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id)
);

CREATE INDEX IF NOT EXISTS idx_menu_items_restaurant_id ON menu_items(restaurant_id);
